### ISSUE TITLE
Gitea on Fly

### ISSUE THREAD

**Issue by SimonLab** [dwyl/gitea-server#1]
see https://blog.gitea.io/2022/04/running-gitea-on-fly.io/

**Comment by nelsonic** [comment]
Nice one. Published last month. Stoked @techknowlogick (contributor to `Gitea`) wrote it! Will be _very_ useful to us. 👍

**Comment by SimonLab** [comment]
- [x] Create app: `flyctl launch --name gitea-server --no-deploy`
 ![image](https://user-images.githubusercontent.com/6057298/168430172-46b18cf9-fb27-4c7a-b340-ce797fdb21c2.png)

- [x] Create volume: `flyctl volumes create gitea_data --size 1 --app gitea-server`
![image](https://user-images.githubusercontent.com/6057298/168430191-bacc718f-19ee-4b18-9e33-8d25ee49579b.png)

- [x] Update fly.toml file to use gitea image

- [ ] ~Use and configure Postgre instead of the defaul sqlite database: https://docs.gitea.io/en-us/database-prep/~

**Comment by nelsonic** [comment]
@SimonLab I actually have nothing against using SQLite on the Server, see: https://github.com/dwyl/technology-stack/issues/92

**Comment by SimonLab** [comment]
gitea server running at: https://gitea-server.fly.dev/

**Comment by nelsonic** [comment]
cURL get repo info:

```sh
 curl 'https://gogs-server.fly.dev/api/v1/repos/myorg/public-repo?token=youraccesstokenhere'
```

Response:
```json
{
	"id": 3,
	"owner": {
		"id": 3,
		"login": "myorg",
		"full_name": "",
		"email": "",
		"avatar_url": "https://gitea-server.fly.dev/avatars/b665280652d01c4679777afd9861170c",
		"language": "",
		"is_admin": false,
		"last_login": "0001-01-01T00:00:00Z",
		"created": "2022-05-15T21:21:42Z",
		"restricted": false,
		"active": false,
		"prohibit_login": false,
		"location": "",
		"website": "",
		"description": "",
		"visibility": "public",
		"followers_count": 0,
		"following_count": 0,
		"starred_repos_count": 0,
		"username": "myorg"
	},
	"name": "public-repo",
	"full_name": "myorg/public-repo",
	"description": "",
	"empty": false,
	"private": false,
	"fork": false,
	"template": false,
	"parent": null,
	"mirror": false,
	"size": 104,
	"html_url": "https://gitea-server.fly.dev/myorg/public-repo",
	"ssh_url": "git@gitea-server.fly.dev:myorg/public-repo.git",
	"clone_url": "https://gitea-server.fly.dev/myorg/public-repo.git",
	"original_url": "",
	"website": "",
	"stars_count": 0,
	"forks_count": 0,
	"watchers_count": 1,
	"open_issues_count": 0,
	"open_pr_counter": 0,
	"release_counter": 0,
	"default_branch": "master",
	"archived": false,
	"created_at": "2022-05-15T21:40:54Z",
	"updated_at": "2022-05-15T21:40:57Z",
	"permissions": {
		"admin": true,
		"push": true,
		"pull": true
	},
	"has_issues": true,
	"internal_tracker": {
		"enable_time_tracker": true,
		"allow_only_contributors_to_track_time": true,
		"enable_issue_dependencies": true
	},
	"has_wiki": true,
	"has_pull_requests": true,
	"has_projects": true,
	"ignore_whitespace_conflicts": false,
	"allow_merge_commits": true,
	"allow_rebase": true,
	"allow_rebase_explicit": true,
	"allow_squash_merge": true,
	"default_merge_style": "merge",
	"avatar_url": "",
	"internal": false,
	"mirror_interval": "",
	"mirror_updated": "0001-01-01T00:00:00Z",
	"repo_transfer": null
}
```

**Comment by nelsonic** [comment]
I've added my `ssh` key: https://gitea-server.fly.dev/user/settings/keys

![image](https://user-images.githubusercontent.com/194400/168495559-1f8649fa-43f7-4f16-a0a2-c09561e10318.png)

But when I attempt to test the connection:

```sh
ssh -T git@gitea-server.fly.dev
```
As per: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/testing-your-ssh-connection

I get:

```sh
Gitea: Internal error
```

@SimonLab please grant me Admin rights on the server so I can investigate. 🙏

**Comment by nelsonic** [comment]
@SimonLab thanks.

```sh
Hi there, nelsonic! You've successfully authenticated with the key named MBP 2022, 
but Gitea does not provide shell access.
If this is unexpected, please log in with password and setup Gitea under another user.
```

`git push` (SSH) works. 

https://gitea-server.fly.dev/myorg/public-repo
![image](https://user-images.githubusercontent.com/194400/168496190-ac48b3de-2c65-406e-83af-dcc7cc570784.png)

**Comment by nelsonic** [comment]
PR: #5 adds detailed docs.
